# Generated by Django 4.0.2 on 2022-02-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_matriculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='matriculas',
        ),
    ]
