name: Instalando os requisitos do Projeto

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'
    - name: Install dependencies
      run: |
        pip install pipenv codecov
        pipenv sync --dev
    - name: Verificar a qualidade do código com Flake8
      uses: py-actions/flake8@v1
      with:
        checkName: 'flake8_py3'
    - name: Rodar os testes no GitHubActions
      run: |
        pipenv run pytest pypro --cov=pypro
    - name: Relatório Coverage
      env:
        CODECOV_TOKEN: 'a72bb601-926d-452a-b4cd-d5b1439a9d39'
      run: |
        pipenv run codecov
